### PR TITLE
new drivers for lcd

### PR DESCRIPTION
**Pull request by mitmarcus**

### CODE REVIEW

**Comment by mitmarcus** [comment]
compiles just fine locally, I will look into it

**Comment by mitmarcus** [comment]
basically win_test doesn't tell the compiler we are on atmega2560
We should rewrite the tests.

**Comment by mitmarcus** [comment]
and the code relies on AVR-specific headers that don't exist in a test environment designed for desktop/host-based testing.

**Review by RubberDuck2307 — APPROVED** [review]
Looks good

**Pull request merged**
